---
- name: Configure systemd-resolved DNS settings
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: "^#?{{ item.option }}="
    line: "{{ item.option }}={{ item.value }}"
    insertafter: '^\[Resolve\]'
  loop:
    - { option: "DNS", value: "172.21.15.150" }
    - { option: "MulticastDNS", value: "no" }
    - { option: "Domains", value: "~hashicorp.local" }
  register: resolved_conf

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
    daemon_reload: yes

- name: sleep for 5 seconds
  ansible.builtin.pause:
    seconds: 5
    
- name: "Launch a workflow and wait for the workflow to finish"
  block:
    - name: Launch a workflow template with extra_vars on remote controller instance when project is set
      awx.awx.workflow_launch:
        controller_host: "aap-aap.apps.openshift-01.hashicorp.local"
        controller_username: "admin"
        controller_password: lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD')
        workflow_template: "eda_workflow"
        extra_vars: "{{ extra_vars |  default(omit, true) }}"
        validate_certs: false
        scm_branch: "{{ scm_branch |  default(omit, true) }}"
      register: workflow_output

    - name: Print out workflow_output
      debug:
        var: workflow_output

    - name: Wait for workflow
      awx.awx.job_wait:
        job_id: "{{ workflow_output.id }}"
        job_type: workflow_jobs
        timeout: 3600
        validate_certs: false