---
# apt upgrade
- name: Update apt cache
  apt:
    update_cache: yes
- name: Upgrade all packages
  apt:
    upgrade: dist
    update_cache: yes
- name: Install gnupg package
  apt:
    name: gnupg
    state: present

- name: Add MongoDB repository
  copy:
    dest: /etc/apt/sources.list.d/mongodb-org.list
    content: |
      deb [signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse
    mode: '0644'

- name: Add OpenVPN repository
  copy:
    dest: /etc/apt/sources.list.d/openvpn.list
    content: |
      deb [signed-by=/usr/share/keyrings/openvpn-repo.gpg] https://build.openvpn.net/debian/openvpn/stable noble main
    mode: '0644'

- name: Add Pritunl repository
  copy:
    dest: /etc/apt/sources.list.d/pritunl.list
    content: |
      deb [signed-by=/usr/share/keyrings/pritunl.gpg] https://repo.pritunl.com/stable/apt jammy main
    mode: '0644'

- name: Download and add MongoDB GPG key
  ansible.builtin.get_url:
    url: https://www.mongodb.org/static/pgp/server-8.0.asc
    dest: /tmp/mongodb-server-8.0.asc

- name: Import MongoDB GPG key
  ansible.builtin.command:
    cmd: gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg --dearmor --yes /tmp/mongodb-server-8.0.asc

- name: Download and add OpenVPN GPG key
  ansible.builtin.get_url:
    url: https://swupdate.openvpn.net/repos/repo-public.gpg
    dest: /tmp/openvpn-repo.gpg

- name: Import OpenVPN GPG key
  ansible.builtin.command:
    cmd: gpg -o /usr/share/keyrings/openvpn-repo.gpg --dearmor --yes /tmp/openvpn-repo.gpg

- name: Download and add Pritunl GPG key
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/pritunl/pgp/master/pritunl_repo_pub.asc
    dest: /tmp/pritunl-repo.asc

- name: Import Pritunl GPG key
  ansible.builtin.command:
    cmd: gpg -o /usr/share/keyrings/pritunl.gpg --dearmor --yes /tmp/pritunl-repo.asc
    

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - pritunl
      - openvpn
      - mongodb-org
      - wireguard
      - wireguard-tools
    state: present

- name: Disable UFW
  ufw:
    state: disabled

- name: Start and enable Pritunl service
  systemd:
    name: pritunl
    state: started
    enabled: yes

- name: Start and enable MongoDB service
  systemd:
    name: mongod
    state: started
    enabled: yes