---
- name: Install Oracle8 JDK
  include_tasks: java_tasks/install_oracle8_jdk.yml
  when:
    - java_version == "oracle:8"
    - ansible_system is match("Linux")

- name: Install Openjdk8 JDK
  include_tasks: java_tasks/install_openjdk8_jdk.yml
  when:
    - java_version == "openjdk:8"
    - ansible_system is match("Linux")

- name: Install Openjdk11 JDK
  include_tasks: java_tasks/install_openjdk11_jdk.yml
  when:
    - java_version == "openjdk:11"
    - ansible_system is match("Linux")

- name: Install Openjdk9 JDK for Windows
  include_tasks: java_tasks/install_openjdk9_jdk_windows.yml
  when:
    - java_version == "openjdk:9"
    - ansible_system is match("CYGWIN*|Win32NT")