---
- name: Remove old manifest files
  file:
    path: "{{ item.path }}"
    state: "absent"
  ignore_errors: yes
  become: yes
  become_user: "{{ privileged_user }}"
  with_items:
  - "{{ manifests.files }}"
  when: splunk_upgrade | bool

- name: Remove old directories
  file:
    path: "{{ item }}"
    state: "absent"
  ignore_errors: yes
  become: yes
  become_user: "{{ privileged_user }}"
  with_items:
    - "{{ splunk.home }}/bin"
    - "{{ splunk.home }}/lib"
    - "{{ splunk.home }}/share"
    - "{{ splunk.home }}/Python-2.7"
  when: splunk_upgrade | bool

- name: Find all files to clean up in Splunk home for fresh install
  find:
    path: "{{ splunk.home }}"
    file_type: file
  ignore_errors: yes
  become: yes
  become_user: "{{ privileged_user }}"
  register: cleanup_files
  when: not splunk_upgrade

- name: Clean up Splunk home for fresh install
  file:
    path: "{{ item.path }}"
    state: "absent"
  ignore_errors: yes
  become: yes
  become_user: "{{ privileged_user }}"
  with_items: "{{ cleanup_files.files }}"
  when: not splunk_upgrade

- name: Install Splunk
  include_tasks: install_splunk_{{ splunk_build_type }}.yml

- name: Remove installers
  file:
    dest: "{{ item }}"
    state: "absent"
  ignore_errors: yes
  become: yes
  become_user: "{{ privileged_user }}"
  with_items:
    - "{{ splunk.build_location }}"
    - "/tmp/splunk.msi"
    - splunk_downloaded_build_location
