---
- name: Install Boundary
  become: true
  apt:
    name: boundary-enterprise
    state: latest

- name: Create Boundary Auth Storage Path
  file:
    state: directory
    path: /opt/boundary
    owner: boundary
    group: boundary
  become: true

- name: Disable Boundary Service
  systemd:
    name: boundary.service
    enabled: no
  become: true
