---
- name: Ensure the .ssh directory exists for vm_user
  ansible.builtin.file:
    path: "/home/vm_user/.ssh"
    state: directory
    mode: "0700"
    owner: vm_user
    group: vm_user

- name: Create authorized_keys file for vm_user if it doesn't exist
  ansible.builtin.file:
    path: "/home/vm_user/.ssh/authorized_keys"
    state: touch
    mode: "0600"
    owner: vm_user
    group: vm_user
    
- name: Create temporary directory for SSH CA storage
  ansible.builtin.file:
    path: /tmp/ssh_ca.d/
    state: directory
    mode: '0755'

- name: Add HashiCorp repo key
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/gpg
    dest: /etc/pki/rpm-gpg/hashicorp-archive-keyring.asc
    mode: "0644"

- name: Add HashiCorp repository
  ansible.builtin.yum_repository:
    name: hashicorp
    description: "HashiCorp Stable - $basearch"
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    gpgkey: file:///etc/pki/rpm-gpg/hashicorp-archive-keyring.asc
    enabled: true

- name: Add docker repo key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/gpg
    dest: /etc/pki/rpm-gpg/docker-archive-keyring.asc
    mode: "0644"

- name: Add docker repository
  ansible.builtin.yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgkey: file:///etc/pki/rpm-gpg/docker-archive-keyring.asc
    enabled: true

- name: Add HCP Vault SSH signing public certificate
  ansible.builtin.get_url:
    url: https://production.vault.11eb56d6-0f95-3a99-a33c-0242ac110007.aws.hashicorp.cloud:8200/v1/ssh/public_key
    headers:
      X-Vault-Namespace: admin/tfo-apj-demos
    dest: /tmp/ssh_ca.d/hcp-vault-ca-keys.pem
    mode: "0644"

- name: Add GCVE Vault SSH signing public certificate
  ansible.builtin.copy:
    content: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC74yY7E3CovzzkfCsO1KJ0WFJL32fMDtooeKkRAazIB4u2zWh0Xy7AuWg8NWOO46KaAiQzDqXFHxe7yq
      xpvfP7XcUlaYtd4znXLVk9PN2VQeBDPrWTn5uIkhFtRafHrbTCIs1JB4aJexKA5+6YKvRv7139mxcQpw4uonQ6+YnVLL+yCarI/ywwcek+ZuFq2Z1yDKGo
      TTfZF2KLDtfjRnRbNB9bzd/tCzRF9SJxOrjHOONtpUmSAhceySF2FcSU1UkneuCFBHgCQq9f93pASPbXw3RSR3NSZMwM7YbsTUyIw2GED4419+qkAV4RHR
      HRNVk5CObEBxu5Wvx1TuPsmcDPWMYOXAiZlOSgtyaX1/x14JnWp8Q0YFhIBkNucCHVcXi4Q4/tZ+ftgakWpUUj3GkeLtdWSCtr58DcR5sEwqALSPHy21ii
      A6qQiJa6/rz3L/Nh3k5UMVMHPhF5358M0vCkN2MuZf66CE1fd4s82g0HfjlOf51H9XPlueECp1NwrbYiWQkpq79VaQCyijlXfvh6S3jKHkkRJArtWrdIt6
      k1jm6gbQUPWsZn6Yb4mXTPGw+tQneZvMP7SLG97JkpwmsLa9OgENz37OpzK2j01QF5C2rB1N3BKkCdm5mW4fQQjNWDirfnCjOshp4tS/lhGFCcqj6w18zF
      YllKx1Z0j5etxw==
    dest: /tmp/ssh_ca.d/gcve-vault-ca-keys.pem
    mode: "0644"

- name: Download PKI CA certificate
  ansible.builtin.get_url:
    url: https://production.vault.11eb56d6-0f95-3a99-a33c-0242ac110007.aws.hashicorp.cloud:8200/v1/pki/ca/pem
    headers:
      X-Vault-Namespace: admin/tfo-apj-demos
    dest: /tmp/ssh_ca.d/hcp-vault-ca.crt
    mode: "0644"

- name: Add CA public certificates
  ansible.builtin.assemble:
    src: /tmp/ssh_ca.d/
    dest: /etc/ssh/trusted-user-ca-keys.pem
    mode: "0644"

- name: Copy CA public certificates to ca-trust
  ansible.builtin.assemble:
    src: /tmp/ssh_ca.d/
    dest: /etc/pki/ca-trust/source/anchors/trusted-user-ca-keys.pem
    mode: "0644"

- name: Update ssh config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    line: TrustedUserCAKeys /etc/ssh/trusted-user-ca-keys.pem

- name: Register HCP Vault CA
  ansible.builtin.command: update-ca-trust extract

- name: SELinux in permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive

####### To install certain packages, the system initially needs to be registered to access.redhat.com

- name: Register the system to access.redhat.com
  community.general.redhat_subscription:
    state: present
    activationkey: "{{ redhat_activation_key }}"
    org_id: "{{ redhat_org_id }}"
  register: subscription_result


- name: Install required packages
  ansible.builtin.package:
    name:
      - sos
      - open-vm-tools
    state: present

- name: Disable root SSH login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"

- name: Create devops user
  ansible.builtin.user:
    name: devops
    groups: wheel
    shell: /bin/bash
    create_home: true

- name: Add sudo rule for devops
  ansible.builtin.copy:
    dest: /etc/sudoers.d/devops
    content: "devops ALL=(ALL) NOPASSWD:ALL\n"
    mode: "0440"