---
# playbook.yaml

- name: "Install packages"
  apt:
    name:
      - "postgresql"
      - "postgresql-contrib"
    update_cache: yes  # this will refresh your repository cache

- name: "Ensure PostgreSQL service is started and enabled"
  service:
    name: postgresql
    state: started
    enabled: yes