---
# playbook.yaml

- name: "Install packages"
  apt:
    name:
      - "postgresql"
      - "postgresql-contrib"
      - "python3-psycopg2"
    update_cache: yes  # this will refresh your repository cache

- name: "Ensure PostgreSQL service is started and enabled"
  service:
    name: postgresql
    state: started
    enabled: yes

- name: "Configure listen_addresses in postgresql.conf"
  lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: '^#?listen_addresses'
    line: "listen_addresses = '*'"
    state: present

- name: "Allow remote connections in pg_hba.conf"
  blockinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    block: |
      host    all             all             0.0.0.0/0                       trust
      host    all             all             ::/0                            md5
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: EOF

- name: "Create user for Vault management"
  postgresql_user:
    name: vault
    password: a12337764bd794a123af5e90b80c2d97
    role_attr_flags: SUPERUSER


- name: "Restart PostgreSQL to apply changes"
  service:
    name: postgresql
    state: restarted
