- name: Check if Docker is installed
  command: docker --version
  register: docker_version
  failed_when: false
  changed_when: false

- name: Set Docker installation status
  set_fact:
    docker_installed: "{{ docker_version.rc == 0 }}"
  when: docker_version.stdout is defined

- block:
    - name: Update packages && install packages to allow apt to use a repository over HTTPS
      apt:
        name: [ca-certificates, curl, gnupg]
        update_cache: yes
        state: present

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update packages and Install docker,containerd,compose
      apt:
        name: [docker-ce, docker-ce-cli, containerd.io, docker-buildx-plugin, docker-compose-plugin]
        update_cache: yes
      notify:
       - Start and Enable docker
  when: docker_installed == false