- name: Install docker, compose
  import_tasks: docker.yaml
  when: docker == true
  tags: [docker]

- name: Configure sysctl parameters for tuning
  import_tasks: sysctl.yaml
  when: sysctl_tuning == true
  tags: [sysctl_tuning]

- name: Install and configure haproxy
  import_tasks: haproxy.yaml
  when: haproxy == true
  tags: [haproxy]

- name: Install and configure keepalived
  import_tasks: keepalived.yaml
  when: keepalived == true
  tags: [keepalived]

- name: Install and configure ufw
  import_tasks: ufw.yaml
  when: ufw == true
  tags: [ufw]

- name: Install Data Plane API
  import_tasks: dataplaneapi.yaml
  when: data_plane_api == true
  tags: [data_plane_api]
