- name: Configure sysctl parameters
  ansible.posix.sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: true
  loop: '{{ sysctl_config }}'

- name: Configure sysctl ufw parameters
  ansible.posix.sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: present
    sysctl_file: /etc/ufw/sysctl.conf
    reload: true
  loop: '{{ sysctl_ufw_config }}'