---
var_system_crypto_policy: !!str DEFAULT:NO-SHA1
inactivity_timeout_value: !!str 900
var_screensaver_lock_delay: !!str 5
var_sudo_logfile: !!str /var/log/sudo.log
var_sudo_timestamp_timeout: !!str 5
var_authselect_profile: !!str sssd
cis_banner_text: !!str Authorized users only. All activity may be monitored and reported.
login_banner_text: !!str >
  ^(Authorized[\s\n]+users[\s\n]+only\.[\s\n]+All[\s\n]+activity[\s\n]+may[\s\n]+be[\s\n]+monitored[\s\n]+and[\s\n]+reported\.|
  ^(?!.*(\\|fedora|rhel|sle|ubuntu)).*)$
var_password_pam_remember: !!str 24
var_password_pam_remember_control_flag: !!str requisite,required
var_accounts_passwords_pam_faillock_deny: !!str 5
var_accounts_passwords_pam_faillock_unlock_time: !!str 900
var_password_pam_dictcheck: !!str 1
var_password_pam_difok: !!str 2
var_password_pam_maxrepeat: !!str 3
var_password_pam_minclass: !!str 4
var_password_pam_minlen: !!str 14
var_password_hashing_algorithm_pam: !!str sha512
var_password_hashing_algorithm: !!str SHA512
var_account_disable_post_pw_expiration: !!str 45
var_accounts_maximum_age_login_defs: !!str 365
var_accounts_password_warn_age_login_defs: !!str 7
var_pam_wheel_group_for_su: !!str sugroup
var_accounts_tmout: !!str 900
var_user_initialization_files_regex: !!str ^\.[\w\- ]+$
var_accounts_user_umask: !!str 027
sysctl_net_ipv6_conf_all_accept_ra_value: !!str 0
sysctl_net_ipv6_conf_all_accept_redirects_value: !!str 0
sysctl_net_ipv6_conf_all_accept_source_route_value: !!str 0
sysctl_net_ipv6_conf_all_forwarding_value: !!str 0
sysctl_net_ipv6_conf_default_accept_ra_value: !!str 0
sysctl_net_ipv6_conf_default_accept_redirects_value: !!str 0
sysctl_net_ipv6_conf_default_accept_source_route_value: !!str 0
sysctl_net_ipv4_conf_all_accept_redirects_value: !!str 0
sysctl_net_ipv4_conf_all_accept_source_route_value: !!str 0
sysctl_net_ipv4_conf_all_log_martians_value: !!str 1
sysctl_net_ipv4_conf_all_rp_filter_value: !!str 1
sysctl_net_ipv4_conf_all_secure_redirects_value: !!str 0
sysctl_net_ipv4_conf_default_accept_redirects_value: !!str 0
sysctl_net_ipv4_conf_default_accept_source_route_value: !!str 0
sysctl_net_ipv4_conf_default_log_martians_value: !!str 1
sysctl_net_ipv4_conf_default_rp_filter_value: !!str 1
sysctl_net_ipv4_conf_default_secure_redirects_value: !!str 0
sysctl_net_ipv4_icmp_echo_ignore_broadcasts_value: !!str 1
sysctl_net_ipv4_icmp_ignore_bogus_error_responses_value: !!str 1
sysctl_net_ipv4_tcp_syncookies_value: !!str 1
var_selinux_policy_name: !!str targeted
var_postfix_inet_interfaces: !!str loopback-only
var_multiple_time_servers: !!str 0.rhel.pool.ntp.org,1.rhel.pool.ntp.org,2.rhel.pool.ntp.org,3.rhel.pool.ntp.org
var_sshd_set_keepalive: !!str 1
sshd_idle_timeout_value: !!str 300
var_sshd_set_login_grace_time: !!str 60
sshd_max_auth_tries_value: !!str 4
var_sshd_max_sessions: !!str 10
var_sshd_set_maxstartups: !!str 10:30:60
sshd_strong_kex: !!str -diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1
sshd_strong_macs: !!str >
  -hmac-md5,hmac-md5-96,hmac-ripemd160,hmac-sha1-96,umac-64@openssh.com,
  hmac-md5-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-ripemd160-etm@openssh.com,
  hmac-sha1-96-etm@openssh.com,umac-64-etm@openssh.com
# Default variables for openscap_report role
# Choose between 'cis_server_l1' or 'essential_8'
openscap_profile: cis_server_l1

# Map of profile keys to OpenSCAP profile IDs
openscap_profile_map:
  cis_server_l1: xccdf_org.ssgproject.content_profile_cis_server_l1
  essential_8: xccdf_org.ssgproject.content_profile_au_essential_8
# Path to the SCAP datastream for RHEL9
openscap_ds_path: /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml