---
- name: "Install Docker packages"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - jq 
      - wget
      - curl 
      - unzip
    update_cache: yes  # this will refresh your repository cache

- name: "Install Helm"
  snap:
    name: helm
    classic: yes

- name: "Install kubectl"
  snap:
    name: kubectl
    classic: yes

- name: "Docker Service"
  systemd:
    name: docker.service
    enabled: yes
    state: started

- name: Add user 'ubuntu' to the 'docker' group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: yes
  become: true

- name: Set timeout for cloud-init
  copy: 
    dest: /etc/cloud/cloud.cfg.d/99-vmware-guest-customization.cfg
    content: |
      datasource_list: [ "VMware" ]
      datasource:
        VMware:
          vmware_cust_file_max_wait: 600

- name: Disable traditional VMware customisation
  lineinfile:
    path: /etc/cloud/cloud.cfg
    state: present
    line: 'disable_vmware_customization: true'

- name: Prepare cloud-init for first use
  command: /usr/bin/cloud-init clean --seed --logs