---
- name: "Install Docker packages"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - jq 
      - wget
      - curl 
      - unzip
    update_cache: yes  # this will refresh your repository cache

- name: "Docker Service"
  systemd:
    name: docker.service
    enabled: yes
    state: started

- name: Use the HashiCorp license
  debug:
    msg: "The HashiCorp license is {{ (role_config | from_json)['tfefdo']['hashicorp_license'] }}"

- name: Use the encryption password
  debug:
    msg: "The encryption password is {{ (role_config | from_json)['tfefdo']['encryption_password'] }}"