name: Build VMware Image

# TODO: Schedule base build.

# on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '30 5,17 * * *'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted, gcve ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Makefile
      run: make ubuntu_2204_base
      env:
        HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
        HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
        HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
        VCENTER_USERNAME: ${{ secrets.VCENTER_USERNAME }}
        VCENTER_PASSWORD: ${{ secrets.VCENTER_PASSWORD }}
        VCENTER_SERVER: ${{ secrets.VCENTER_SERVER }}
