name: Build VMware Base Images

# TODO: Schedule base build.

on:
  workflow_dispatch:
  schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '30 5,17 * * *'
    - cron:  '0 10 * * SUN' # UTC TIME

env:
  HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
  HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
  HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
  VCENTER_USERNAME: ${{ secrets.VCENTER_USERNAME }}
  VCENTER_PASSWORD: ${{ secrets.VCENTER_PASSWORD }}
  VCENTER_SERVER: ${{ secrets.VCENTER_SERVER }}
    
jobs:
  ubuntu_2204_base:
    runs-on: [ self-hosted, gcve ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Makefile
      run: make ubuntu_2204_base

  ubuntu_2204_vault:
    runs-on: [ self-hosted, gcve ]
    needs: ubuntu_2204_base

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Makefile
      run: make ubuntu_2204_vault
  
  ubuntu_2204_postgres:
    runs-on: [ self-hosted, gcve ]
    needs: ubuntu_2204_base

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Makefile
      run: make ubuntu_2204_postgres
      
