name: Build VMware Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted, gcve ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        echo "VCENTER_USERNAME=${{ secrets.VCENTER_USERNAME }}" >> $GITHUB_ENV
        echo "VCENTER_PASSWORD=${{ secrets.VCENTER_PASSWORD }}" >> $GITHUB_ENV
        echo "VCENTER_SERVER=${{ secrets.VCENTER_SERVER }}" >> $GITHUB_ENV
        echo "HCP_CLIENT_ID=${{ secrets.HCP_CLIENT_ID }}" >> $GITHUB_ENV
        echo "HCP_CLIENT_SECRET=${{ secrets.HCP_CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "HCP_PROJECT_ID=${{ secrets.HCP_PROJECT_ID }}" >> $GITHUB_ENV

    - name: Run Makefile
      run: make ubuntu_2204_base
