name: Build VMware App Images

on:
  workflow_dispatch:
    inputs:
      singleBuild:
        type: choice
        description: image override
        required: false
        options:
          - all
          - ubuntu_2204_vault
          - ubuntu_2204_postgres
          - ubuntu_2204_docker
          - ubuntu_2204_haproxy
  schedule:
   - cron:  '0 11 * * SUN' # UTC TIME

env:
  DEFAULT_IMAGES: ubuntu_2204_vault, ubuntu_2204_postgres, ubuntu_2204_docker, ubuntu_2204_haproxy
  HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
  HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
  HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
  VCENTER_USERNAME: ${{ secrets.VCENTER_USERNAME }}
  VCENTER_PASSWORD: ${{ secrets.VCENTER_PASSWORD }}
  VCENTER_SERVER: ${{ secrets.VCENTER_SERVER }}
    
jobs:
  selectimages:
    runs-on: "ubuntu-latest"
    steps:
      - name: get-images
        id: get-images
        run: |
          if [[ "${{inputs.singleBuild}}" != "all" ]]; then
            export IMAGES=$(echo ${{inputs.singleBuild}} | jq -R '["\(.)"]' )
            echo "images=$IMAGES" >> $GITHUB_OUTPUT
          else
            export IMAGES=$(echo $DEFAULT_IMAGES | jq -R 'split(", ")')
            echo "images=$IMAGES" >> $GITHUB_OUTPUT
          fi
    outputs:
      images: ${{toJson(steps.get-images.outputs.images)}}

  build:
    runs-on: [self-hosted, gcve]
    needs: [selectimages]
    strategy:
      matrix:
        image_type: ${{fromJson(needs.selectimages.outputs.images)}}
          #[ubuntu_2204_vault, ubuntu_2204_postgres, ubuntu_2204_docker, ubuntu_2204_haproxy]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Makefile
        run: make ${{ matrix.image_type }}
      
