name: Build VMware App Images

on:
  workflow_dispatch:
    inputs:
      singleBuild:
        type: choice
        description: image override
        required: false
        options:
          - all
          - ubuntu_2204_vault
          - ubuntu_2204_postgres
          - ubuntu_2204_docker
          - ubuntu_2204_haproxy
          - ubuntu_2204_tfefdo
          - windows_2022_mssql
  schedule:
   - cron:  '0 11 * * SUN' # UTC TIME

env:
  DEFAULT_IMAGES: ubuntu_2204_vault, ubuntu_2204_postgres, ubuntu_2204_docker, ubuntu_2204_haproxy, ubuntu_2204_tfefdo
  HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
  HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
  HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
  VCENTER_USERNAME: ${{ secrets.VCENTER_USERNAME }}
  VCENTER_PASSWORD: ${{ secrets.VCENTER_PASSWORD }}
  VCENTER_SERVER: ${{ secrets.VCENTER_SERVER }}
  ROLE_CONFIG: ${{ secrets.ROLE_CONFIG }}
  WINDOWS_PASSWORD: ${{secrets.WINDOWS_PASSWORD}}
  LINUX_PASSWORD: ${{secrets.LINUX_PASSWORD}}
    
jobs:
  selectimages:
    runs-on: "ubuntu-latest"
    steps:
      - name: get-images
        id: get-images
        if: ${{ github.event.inputs.singleBuild != '' }}
        run: |
          if [[ "${{ inputs.singleBuild }}" != "all" ]] && [[ -n "${{ github.event.inputs.singleBuild }}" ]]; then
            export IMAGES=$(echo ${{ inputs.singleBuild }} | jq -R '["\(.)"]')
            echo "images_out"=$IMAGES""
            echo "images_out"=$IMAGES"" >> $GITHUB_OUTPUT
          else
            export IMAGES=$(echo $DEFAULT_IMAGES | jq -R 'split(", ")')
            echo "images_out"=$IMAGES""
            echo "images_out"=$IMAGES"" >> $GITHUB_OUTPUT
          fi
    outputs:
      images: ${{ steps.get-images.outputs.images_out }}

  build:
    runs-on: [self-hosted, gcve]
    needs: [selectimages]
    strategy:
      matrix:
        image_type: ${{fromJson(needs.selectimages.outputs.images)}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        
      - name: Run Makefile
        run: make ${{ matrix.image_type }}
      
